# Preguntas de SQL

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("shows.db")

In [2]:
#Pregunta 1: ¿Cuántas series tienen una calificación perfecta de 10.0?

query = """
SELECT COUNT(*)
FROM ratings
WHERE rating = 10.0;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0        27

In [8]:
#Pregunta 2: ¿Cuántos episodios tiene Black Mirror?

query = """
SELECT episodes
FROM shows
WHERE title = 'Black Mirror';
"""

pd.read_sql_query(query, conn)

   episodes
0        22

In [9]:
#Pregunta 3: ¿Cuántas series existen en el género ciencia ficción?

query = """
SELECT COUNT(DISTINCT show_id)
FROM genres
WHERE genre = 'Sci-Fi';
"""

pd.read_sql_query(query, conn)

   COUNT(DISTINCT show_id)
0                     3275

In [10]:
#Pregunta 4: ¿Cuál es la serie mejor valorada del género de terror?

query = """
SELECT s.title, r.rating
FROM shows s
JOIN genres g ON s.id = g.show_id
JOIN ratings r ON s.id = r.show_id
WHERE g.genre = 'Horror'
ORDER BY r.rating DESC
LIMIT 1;
"""

pd.read_sql_query(query, conn)

       title  rating
0  O Kapoios    10.0

In [11]:
#Pregunta 5: ¿Cuántas series de animación hay en la base de datos?

query = """
SELECT COUNT(DISTINCT show_id) AS n_animation
FROM genres
WHERE genre = 'Animation';
"""

pd.read_sql_query(query, conn)

   n_animation
0         4470

In [12]:
#Pregunta 6: ¿Cuáles fueron las 10 series de animación peor valoradas entre 2005 y 2010?

query = """
SELECT s.title,
       s.year,
       r.rating
FROM shows s
JOIN genres g ON s.id = g.show_id
JOIN ratings r ON s.id = r.show_id
WHERE g.genre = 'Animation'
  AND s.year BETWEEN 2005 AND 2010
ORDER BY r.rating ASC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                         title  year  rating
0            Hime-sama Goyojin  2006     2.8
1                  Mighty Raju  2010     3.1
2                   My Life Me  2010     3.4
3              The Samsonadzes  2009     3.4
4                    Randoslap  2005     3.4
5                   Toasted TV  2005     3.7
6  Winner and the Golden Child  2008     3.8
7                      Vezuha!  2010     3.9
8               Angus & Cheryl  2006     4.0
9              Angel's Feather  2006     4.3

# Preguntas de SDSS