# Preguntas de SQL

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("shows.db")

In [2]:
#Pregunta 1: ¿Cuántas series tienen una calificación perfecta de 10.0?

query = """
SELECT COUNT(*)
FROM ratings
WHERE rating = 10.0;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0        27

In [8]:
#Pregunta 2: ¿Cuántos episodios tiene Black Mirror?

query = """
SELECT episodes
FROM shows
WHERE title = 'Black Mirror';
"""

pd.read_sql_query(query, conn)

   episodes
0        22

In [9]:
#Pregunta 3: ¿Cuántas series existen en el género ciencia ficción?

query = """
SELECT COUNT(DISTINCT show_id)
FROM genres
WHERE genre = 'Sci-Fi';
"""

pd.read_sql_query(query, conn)

   COUNT(DISTINCT show_id)
0                     3275

In [10]:
#Pregunta 4: ¿Cuál es la serie mejor valorada del género de terror?

query = """
SELECT s.title, r.rating
FROM shows s
JOIN genres g ON s.id = g.show_id
JOIN ratings r ON s.id = r.show_id
WHERE g.genre = 'Horror'
ORDER BY r.rating DESC
LIMIT 1;
"""

pd.read_sql_query(query, conn)

       title  rating
0  O Kapoios    10.0

In [11]:
#Pregunta 5: ¿Cuántas series de animación hay en la base de datos?

query = """
SELECT COUNT(DISTINCT show_id) AS n_animation
FROM genres
WHERE genre = 'Animation';
"""

pd.read_sql_query(query, conn)

   n_animation
0         4470

In [12]:
#Pregunta 6: ¿Cuáles fueron las 10 series de animación peor valoradas entre 2005 y 2010?

query = """
SELECT s.title,
       s.year,
       r.rating
FROM shows s
JOIN genres g ON s.id = g.show_id
JOIN ratings r ON s.id = r.show_id
WHERE g.genre = 'Animation'
  AND s.year BETWEEN 2005 AND 2010
ORDER BY r.rating ASC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                         title  year  rating
0            Hime-sama Goyojin  2006     2.8
1                  Mighty Raju  2010     3.1
2                   My Life Me  2010     3.4
3              The Samsonadzes  2009     3.4
4                    Randoslap  2005     3.4
5                   Toasted TV  2005     3.7
6  Winner and the Golden Child  2008     3.8
7                      Vezuha!  2010     3.9
8               Angus & Cheryl  2006     4.0
9              Angel's Feather  2006     4.3

# Preguntas de SDSS

In [17]:
from astroquery.sdss import SDSS
import pandas as pd

In [18]:
#Pregunta 1: Encuentra galaxias cerca de RA=141 más brillantes que g=18 y recupera ObjID, RA, DEC y las cinco magnitudes.

query1 = """
SELECT TOP 50
    p.objID,
    p.ra,
    p.dec,
    p.u,
    p.g,
    p.r,
    p.i,
    p.z
FROM PhotoObj AS p
WHERE
    ABS(p.ra - 141.0) < 0.5
    AND p.g < 18
ORDER BY p.g ASC
"""

result1 = SDSS.query_sql(query1)

df1 = result1.to_pandas()
df1.head()

,objID,ra,dec,u,g,r,i,z
0,1237660962940911680,141.092323,36.586534,24.63455,-9999.0,13.03452,13.18112,22.82684
1,1237654383589982308,140.974556,55.227036,21.74032,-9999.0,18.83426,18.56289,18.02747
2,1237650796217566274,140.526732,-0.004363,24.97551,-9999.0,22.40556,21.46568,-9999.00000
3,1237650796754829593,141.406506,0.415136,19.90715,-9999.0,17.86511,17.64208,-9999.00000
4,1237650797291635769,141.343372,0.834825,25.06962,-9999.0,22.94853,21.18559,-9999.00000

In [19]:
# Pregunta 2: Busca cuásares con espectros donde z > 4.5 y zWarning=0. ¿Cuál tiene el mayor corrimiento al rojo?

query2 = """
SELECT TOP 1
    s.specObjID,
    s.ra,
    s.dec,
    s.z
FROM SpecObj AS s
WHERE
    s.class = 'QSO'
    AND s.z > 4.5
    AND s.zWarning = 0
ORDER BY s.z DESC
"""

result2 = SDSS.query_sql(query2)

df2 = result2.to_pandas()
df2

             specObjID         ra        dec         z
0  6604651000581347328  200.99695  17.910995  7.042325

In [20]:
#Pregunta 3: Devuelve solo galaxias entre RA=140.25–140.75 y DEC=20.25–20.75

query3 = """
SELECT TOP 100
    p.objID,
    p.ra,
    p.dec
FROM PhotoObj AS p
WHERE
    p.type = 3
    AND p.ra BETWEEN 140.25 AND 140.75
    AND p.dec BETWEEN 20.25 AND 20.75
"""

result3 = SDSS.query_sql(query3)

df3 = result3.to_pandas()
df3.head()

                 objID          ra        dec
0  1237667430630556668  140.250818  20.699612
1  1237667293189964556  140.250897  20.460677
2  1237667430630555782  140.250934  20.520193
3  1237667430630556719  140.251133  20.592271
4  1237667430630555695  140.251270  20.628143